# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import bff_pb2 as protos_dot_bff__pb2
from protos import types_pb2 as protos_dot_types__pb2


class BFFStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ResetServer = channel.unary_unary(
            '/game.bff.BFF/ResetServer',
            request_serializer=protos_dot_types__pb2.CommonRequest.SerializeToString,
            response_deserializer=protos_dot_types__pb2.CommonResponse.FromString,
        )
        self.RegisterService = channel.unary_unary(
            '/game.bff.BFF/RegisterService',
            request_serializer=protos_dot_bff__pb2.ServiceInfoList.SerializeToString,
            response_deserializer=protos_dot_bff__pb2.ServiceIdList.FromString,
        )
        self.UnRegisterService = channel.unary_unary(
            '/game.bff.BFF/UnRegisterService',
            request_serializer=protos_dot_bff__pb2.ServiceIdList.SerializeToString,
            response_deserializer=protos_dot_types__pb2.CommonResponse.FromString,
        )
        self.GetServiceInfo = channel.unary_unary(
            '/game.bff.BFF/GetServiceInfo',
            request_serializer=protos_dot_bff__pb2.ServiceIdList.SerializeToString,
            response_deserializer=protos_dot_bff__pb2.ServiceInfoMap.FromString,
        )
        self.SetServiceInfo = channel.unary_unary(
            '/game.bff.BFF/SetServiceInfo',
            request_serializer=protos_dot_bff__pb2.ServiceInfoMap.SerializeToString,
            response_deserializer=protos_dot_types__pb2.CommonResponse.FromString,
        )
        self.GetDataConfig = channel.unary_unary(
            '/game.bff.BFF/GetDataConfig',
            request_serializer=protos_dot_types__pb2.CommonRequest.SerializeToString,
            response_deserializer=protos_dot_bff__pb2.DataConfig.FromString,
        )
        self.SetDataConfig = channel.unary_unary(
            '/game.bff.BFF/SetDataConfig',
            request_serializer=protos_dot_bff__pb2.DataConfig.SerializeToString,
            response_deserializer=protos_dot_types__pb2.CommonResponse.FromString,
        )
        self.ProxyChat = channel.stream_stream(
            '/game.bff.BFF/ProxyChat',
            request_serializer=protos_dot_types__pb2.JsonString.SerializeToString,
            response_deserializer=protos_dot_types__pb2.JsonString.FromString,
        )
        self.GetRouteConfig = channel.unary_unary(
            '/game.bff.BFF/GetRouteConfig',
            request_serializer=protos_dot_types__pb2.CommonRequest.SerializeToString,
            response_deserializer=protos_dot_bff__pb2.RouteConfig.FromString,
        )
        self.SetRouteConfig = channel.unary_unary(
            '/game.bff.BFF/SetRouteConfig',
            request_serializer=protos_dot_bff__pb2.RouteConfig.SerializeToString,
            response_deserializer=protos_dot_types__pb2.CommonResponse.FromString,
        )
        self.GetAgentConfig = channel.unary_unary(
            '/game.bff.BFF/GetAgentConfig',
            request_serializer=protos_dot_bff__pb2.ServiceIdList.SerializeToString,
            response_deserializer=protos_dot_bff__pb2.AgentConfigMap.FromString,
        )
        self.SetAgentConfig = channel.unary_unary(
            '/game.bff.BFF/SetAgentConfig',
            request_serializer=protos_dot_bff__pb2.AgentConfigMap.SerializeToString,
            response_deserializer=protos_dot_types__pb2.CommonResponse.FromString,
        )
        self.GetAgentMode = channel.unary_unary(
            '/game.bff.BFF/GetAgentMode',
            request_serializer=protos_dot_bff__pb2.ServiceIdList.SerializeToString,
            response_deserializer=protos_dot_bff__pb2.AgentModeMap.FromString,
        )
        self.SetAgentMode = channel.unary_unary(
            '/game.bff.BFF/SetAgentMode',
            request_serializer=protos_dot_bff__pb2.AgentModeMap.SerializeToString,
            response_deserializer=protos_dot_types__pb2.CommonResponse.FromString,
        )
        self.GetAgentWeight = channel.unary_unary(
            '/game.bff.BFF/GetAgentWeight',
            request_serializer=protos_dot_bff__pb2.ServiceIdList.SerializeToString,
            response_deserializer=protos_dot_bff__pb2.AgentWeightMap.FromString,
        )
        self.SetAgentWeight = channel.unary_unary(
            '/game.bff.BFF/SetAgentWeight',
            request_serializer=protos_dot_bff__pb2.AgentWeightMap.SerializeToString,
            response_deserializer=protos_dot_types__pb2.CommonResponse.FromString,
        )
        self.GetAgentBuffer = channel.unary_unary(
            '/game.bff.BFF/GetAgentBuffer',
            request_serializer=protos_dot_bff__pb2.ServiceIdList.SerializeToString,
            response_deserializer=protos_dot_bff__pb2.AgentBufferMap.FromString,
        )
        self.SetAgentBuffer = channel.unary_unary(
            '/game.bff.BFF/SetAgentBuffer',
            request_serializer=protos_dot_bff__pb2.AgentBufferMap.SerializeToString,
            response_deserializer=protos_dot_types__pb2.CommonResponse.FromString,
        )
        self.GetAgentStatus = channel.unary_unary(
            '/game.bff.BFF/GetAgentStatus',
            request_serializer=protos_dot_bff__pb2.ServiceIdList.SerializeToString,
            response_deserializer=protos_dot_bff__pb2.AgentStatusMap.FromString,
        )
        self.SetAgentStatus = channel.unary_unary(
            '/game.bff.BFF/SetAgentStatus',
            request_serializer=protos_dot_bff__pb2.AgentStatusMap.SerializeToString,
            response_deserializer=protos_dot_types__pb2.CommonResponse.FromString,
        )
        self.SimControl = channel.unary_unary(
            '/game.bff.BFF/SimControl',
            request_serializer=protos_dot_bff__pb2.SimCmd.SerializeToString,
            response_deserializer=protos_dot_types__pb2.CommonResponse.FromString,
        )
        self.SimMonitor = channel.unary_unary(
            '/game.bff.BFF/SimMonitor',
            request_serializer=protos_dot_types__pb2.CommonRequest.SerializeToString,
            response_deserializer=protos_dot_bff__pb2.SimInfo.FromString,
        )


class BFFServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ResetServer(self, request, context):
        """重置BFF服务
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterService(self, request, context):
        """注册服务
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnRegisterService(self, request, context):
        """注销服务
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServiceInfo(self, request, context):
        """获取服务信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetServiceInfo(self, request, context):
        """设置服务信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDataConfig(self, request, context):
        """获取数据配置
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDataConfig(self, request, context):
        """设置数据配置
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProxyChat(self, request_iterator, context):
        """智能代理流式通信
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRouteConfig(self, request, context):
        """获取路由配置
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRouteConfig(self, request, context):
        """设置路由配置
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgentConfig(self, request, context):
        """获取智能体配置
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAgentConfig(self, request, context):
        """设置智能体配置
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgentMode(self, request, context):
        """设置智能体模式
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAgentMode(self, request, context):
        """设置智能体模式
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgentWeight(self, request, context):
        """获取智能体权重
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAgentWeight(self, request, context):
        """设置智能体权重
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgentBuffer(self, request, context):
        """获取智能体经验池
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAgentBuffer(self, request, context):
        """设置智能体经验池
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgentStatus(self, request, context):
        """获取智能体状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAgentStatus(self, request, context):
        """设置智能体状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SimControl(self, request, context):
        """控制仿真流程
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SimMonitor(self, request, context):
        """获取仿真信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BFFServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'ResetServer':
            grpc.unary_unary_rpc_method_handler(
                servicer.ResetServer,
                request_deserializer=protos_dot_types__pb2.CommonRequest.FromString,
                response_serializer=protos_dot_types__pb2.CommonResponse.SerializeToString,
            ),
        'RegisterService':
            grpc.unary_unary_rpc_method_handler(
                servicer.RegisterService,
                request_deserializer=protos_dot_bff__pb2.ServiceInfoList.FromString,
                response_serializer=protos_dot_bff__pb2.ServiceIdList.SerializeToString,
            ),
        'UnRegisterService':
            grpc.unary_unary_rpc_method_handler(
                servicer.UnRegisterService,
                request_deserializer=protos_dot_bff__pb2.ServiceIdList.FromString,
                response_serializer=protos_dot_types__pb2.CommonResponse.SerializeToString,
            ),
        'GetServiceInfo':
            grpc.unary_unary_rpc_method_handler(
                servicer.GetServiceInfo,
                request_deserializer=protos_dot_bff__pb2.ServiceIdList.FromString,
                response_serializer=protos_dot_bff__pb2.ServiceInfoMap.SerializeToString,
            ),
        'SetServiceInfo':
            grpc.unary_unary_rpc_method_handler(
                servicer.SetServiceInfo,
                request_deserializer=protos_dot_bff__pb2.ServiceInfoMap.FromString,
                response_serializer=protos_dot_types__pb2.CommonResponse.SerializeToString,
            ),
        'GetDataConfig':
            grpc.unary_unary_rpc_method_handler(
                servicer.GetDataConfig,
                request_deserializer=protos_dot_types__pb2.CommonRequest.FromString,
                response_serializer=protos_dot_bff__pb2.DataConfig.SerializeToString,
            ),
        'SetDataConfig':
            grpc.unary_unary_rpc_method_handler(
                servicer.SetDataConfig,
                request_deserializer=protos_dot_bff__pb2.DataConfig.FromString,
                response_serializer=protos_dot_types__pb2.CommonResponse.SerializeToString,
            ),
        'ProxyChat':
            grpc.stream_stream_rpc_method_handler(
                servicer.ProxyChat,
                request_deserializer=protos_dot_types__pb2.JsonString.FromString,
                response_serializer=protos_dot_types__pb2.JsonString.SerializeToString,
            ),
        'GetRouteConfig':
            grpc.unary_unary_rpc_method_handler(
                servicer.GetRouteConfig,
                request_deserializer=protos_dot_types__pb2.CommonRequest.FromString,
                response_serializer=protos_dot_bff__pb2.RouteConfig.SerializeToString,
            ),
        'SetRouteConfig':
            grpc.unary_unary_rpc_method_handler(
                servicer.SetRouteConfig,
                request_deserializer=protos_dot_bff__pb2.RouteConfig.FromString,
                response_serializer=protos_dot_types__pb2.CommonResponse.SerializeToString,
            ),
        'GetAgentConfig':
            grpc.unary_unary_rpc_method_handler(
                servicer.GetAgentConfig,
                request_deserializer=protos_dot_bff__pb2.ServiceIdList.FromString,
                response_serializer=protos_dot_bff__pb2.AgentConfigMap.SerializeToString,
            ),
        'SetAgentConfig':
            grpc.unary_unary_rpc_method_handler(
                servicer.SetAgentConfig,
                request_deserializer=protos_dot_bff__pb2.AgentConfigMap.FromString,
                response_serializer=protos_dot_types__pb2.CommonResponse.SerializeToString,
            ),
        'GetAgentMode':
            grpc.unary_unary_rpc_method_handler(
                servicer.GetAgentMode,
                request_deserializer=protos_dot_bff__pb2.ServiceIdList.FromString,
                response_serializer=protos_dot_bff__pb2.AgentModeMap.SerializeToString,
            ),
        'SetAgentMode':
            grpc.unary_unary_rpc_method_handler(
                servicer.SetAgentMode,
                request_deserializer=protos_dot_bff__pb2.AgentModeMap.FromString,
                response_serializer=protos_dot_types__pb2.CommonResponse.SerializeToString,
            ),
        'GetAgentWeight':
            grpc.unary_unary_rpc_method_handler(
                servicer.GetAgentWeight,
                request_deserializer=protos_dot_bff__pb2.ServiceIdList.FromString,
                response_serializer=protos_dot_bff__pb2.AgentWeightMap.SerializeToString,
            ),
        'SetAgentWeight':
            grpc.unary_unary_rpc_method_handler(
                servicer.SetAgentWeight,
                request_deserializer=protos_dot_bff__pb2.AgentWeightMap.FromString,
                response_serializer=protos_dot_types__pb2.CommonResponse.SerializeToString,
            ),
        'GetAgentBuffer':
            grpc.unary_unary_rpc_method_handler(
                servicer.GetAgentBuffer,
                request_deserializer=protos_dot_bff__pb2.ServiceIdList.FromString,
                response_serializer=protos_dot_bff__pb2.AgentBufferMap.SerializeToString,
            ),
        'SetAgentBuffer':
            grpc.unary_unary_rpc_method_handler(
                servicer.SetAgentBuffer,
                request_deserializer=protos_dot_bff__pb2.AgentBufferMap.FromString,
                response_serializer=protos_dot_types__pb2.CommonResponse.SerializeToString,
            ),
        'GetAgentStatus':
            grpc.unary_unary_rpc_method_handler(
                servicer.GetAgentStatus,
                request_deserializer=protos_dot_bff__pb2.ServiceIdList.FromString,
                response_serializer=protos_dot_bff__pb2.AgentStatusMap.SerializeToString,
            ),
        'SetAgentStatus':
            grpc.unary_unary_rpc_method_handler(
                servicer.SetAgentStatus,
                request_deserializer=protos_dot_bff__pb2.AgentStatusMap.FromString,
                response_serializer=protos_dot_types__pb2.CommonResponse.SerializeToString,
            ),
        'SimControl':
            grpc.unary_unary_rpc_method_handler(
                servicer.SimControl,
                request_deserializer=protos_dot_bff__pb2.SimCmd.FromString,
                response_serializer=protos_dot_types__pb2.CommonResponse.SerializeToString,
            ),
        'SimMonitor':
            grpc.unary_unary_rpc_method_handler(
                servicer.SimMonitor,
                request_deserializer=protos_dot_types__pb2.CommonRequest.FromString,
                response_serializer=protos_dot_bff__pb2.SimInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler('game.bff.BFF', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class BFF(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ResetServer(request,
                    target,
                    options=(),
                    channel_credentials=None,
                    call_credentials=None,
                    insecure=False,
                    compression=None,
                    wait_for_ready=None,
                    timeout=None,
                    metadata=None):
        return grpc.experimental.unary_unary(request, target, '/game.bff.BFF/ResetServer',
                                             protos_dot_types__pb2.CommonRequest.SerializeToString,
                                             protos_dot_types__pb2.CommonResponse.FromString, options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegisterService(request,
                        target,
                        options=(),
                        channel_credentials=None,
                        call_credentials=None,
                        insecure=False,
                        compression=None,
                        wait_for_ready=None,
                        timeout=None,
                        metadata=None):
        return grpc.experimental.unary_unary(request, target, '/game.bff.BFF/RegisterService',
                                             protos_dot_bff__pb2.ServiceInfoList.SerializeToString,
                                             protos_dot_bff__pb2.ServiceIdList.FromString, options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UnRegisterService(request,
                          target,
                          options=(),
                          channel_credentials=None,
                          call_credentials=None,
                          insecure=False,
                          compression=None,
                          wait_for_ready=None,
                          timeout=None,
                          metadata=None):
        return grpc.experimental.unary_unary(request, target, '/game.bff.BFF/UnRegisterService',
                                             protos_dot_bff__pb2.ServiceIdList.SerializeToString,
                                             protos_dot_types__pb2.CommonResponse.FromString, options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetServiceInfo(request,
                       target,
                       options=(),
                       channel_credentials=None,
                       call_credentials=None,
                       insecure=False,
                       compression=None,
                       wait_for_ready=None,
                       timeout=None,
                       metadata=None):
        return grpc.experimental.unary_unary(request, target, '/game.bff.BFF/GetServiceInfo',
                                             protos_dot_bff__pb2.ServiceIdList.SerializeToString,
                                             protos_dot_bff__pb2.ServiceInfoMap.FromString, options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetServiceInfo(request,
                       target,
                       options=(),
                       channel_credentials=None,
                       call_credentials=None,
                       insecure=False,
                       compression=None,
                       wait_for_ready=None,
                       timeout=None,
                       metadata=None):
        return grpc.experimental.unary_unary(request, target, '/game.bff.BFF/SetServiceInfo',
                                             protos_dot_bff__pb2.ServiceInfoMap.SerializeToString,
                                             protos_dot_types__pb2.CommonResponse.FromString, options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDataConfig(request,
                      target,
                      options=(),
                      channel_credentials=None,
                      call_credentials=None,
                      insecure=False,
                      compression=None,
                      wait_for_ready=None,
                      timeout=None,
                      metadata=None):
        return grpc.experimental.unary_unary(request, target, '/game.bff.BFF/GetDataConfig',
                                             protos_dot_types__pb2.CommonRequest.SerializeToString,
                                             protos_dot_bff__pb2.DataConfig.FromString, options, channel_credentials, insecure,
                                             call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetDataConfig(request,
                      target,
                      options=(),
                      channel_credentials=None,
                      call_credentials=None,
                      insecure=False,
                      compression=None,
                      wait_for_ready=None,
                      timeout=None,
                      metadata=None):
        return grpc.experimental.unary_unary(request, target, '/game.bff.BFF/SetDataConfig',
                                             protos_dot_bff__pb2.DataConfig.SerializeToString,
                                             protos_dot_types__pb2.CommonResponse.FromString, options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ProxyChat(request_iterator,
                  target,
                  options=(),
                  channel_credentials=None,
                  call_credentials=None,
                  insecure=False,
                  compression=None,
                  wait_for_ready=None,
                  timeout=None,
                  metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/game.bff.BFF/ProxyChat',
                                               protos_dot_types__pb2.JsonString.SerializeToString,
                                               protos_dot_types__pb2.JsonString.FromString, options, channel_credentials,
                                               insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRouteConfig(request,
                       target,
                       options=(),
                       channel_credentials=None,
                       call_credentials=None,
                       insecure=False,
                       compression=None,
                       wait_for_ready=None,
                       timeout=None,
                       metadata=None):
        return grpc.experimental.unary_unary(request, target, '/game.bff.BFF/GetRouteConfig',
                                             protos_dot_types__pb2.CommonRequest.SerializeToString,
                                             protos_dot_bff__pb2.RouteConfig.FromString, options, channel_credentials, insecure,
                                             call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetRouteConfig(request,
                       target,
                       options=(),
                       channel_credentials=None,
                       call_credentials=None,
                       insecure=False,
                       compression=None,
                       wait_for_ready=None,
                       timeout=None,
                       metadata=None):
        return grpc.experimental.unary_unary(request, target, '/game.bff.BFF/SetRouteConfig',
                                             protos_dot_bff__pb2.RouteConfig.SerializeToString,
                                             protos_dot_types__pb2.CommonResponse.FromString, options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAgentConfig(request,
                       target,
                       options=(),
                       channel_credentials=None,
                       call_credentials=None,
                       insecure=False,
                       compression=None,
                       wait_for_ready=None,
                       timeout=None,
                       metadata=None):
        return grpc.experimental.unary_unary(request, target, '/game.bff.BFF/GetAgentConfig',
                                             protos_dot_bff__pb2.ServiceIdList.SerializeToString,
                                             protos_dot_bff__pb2.AgentConfigMap.FromString, options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetAgentConfig(request,
                       target,
                       options=(),
                       channel_credentials=None,
                       call_credentials=None,
                       insecure=False,
                       compression=None,
                       wait_for_ready=None,
                       timeout=None,
                       metadata=None):
        return grpc.experimental.unary_unary(request, target, '/game.bff.BFF/SetAgentConfig',
                                             protos_dot_bff__pb2.AgentConfigMap.SerializeToString,
                                             protos_dot_types__pb2.CommonResponse.FromString, options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAgentMode(request,
                     target,
                     options=(),
                     channel_credentials=None,
                     call_credentials=None,
                     insecure=False,
                     compression=None,
                     wait_for_ready=None,
                     timeout=None,
                     metadata=None):
        return grpc.experimental.unary_unary(request, target, '/game.bff.BFF/GetAgentMode',
                                             protos_dot_bff__pb2.ServiceIdList.SerializeToString,
                                             protos_dot_bff__pb2.AgentModeMap.FromString, options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetAgentMode(request,
                     target,
                     options=(),
                     channel_credentials=None,
                     call_credentials=None,
                     insecure=False,
                     compression=None,
                     wait_for_ready=None,
                     timeout=None,
                     metadata=None):
        return grpc.experimental.unary_unary(request, target, '/game.bff.BFF/SetAgentMode',
                                             protos_dot_bff__pb2.AgentModeMap.SerializeToString,
                                             protos_dot_types__pb2.CommonResponse.FromString, options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAgentWeight(request,
                       target,
                       options=(),
                       channel_credentials=None,
                       call_credentials=None,
                       insecure=False,
                       compression=None,
                       wait_for_ready=None,
                       timeout=None,
                       metadata=None):
        return grpc.experimental.unary_unary(request, target, '/game.bff.BFF/GetAgentWeight',
                                             protos_dot_bff__pb2.ServiceIdList.SerializeToString,
                                             protos_dot_bff__pb2.AgentWeightMap.FromString, options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetAgentWeight(request,
                       target,
                       options=(),
                       channel_credentials=None,
                       call_credentials=None,
                       insecure=False,
                       compression=None,
                       wait_for_ready=None,
                       timeout=None,
                       metadata=None):
        return grpc.experimental.unary_unary(request, target, '/game.bff.BFF/SetAgentWeight',
                                             protos_dot_bff__pb2.AgentWeightMap.SerializeToString,
                                             protos_dot_types__pb2.CommonResponse.FromString, options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAgentBuffer(request,
                       target,
                       options=(),
                       channel_credentials=None,
                       call_credentials=None,
                       insecure=False,
                       compression=None,
                       wait_for_ready=None,
                       timeout=None,
                       metadata=None):
        return grpc.experimental.unary_unary(request, target, '/game.bff.BFF/GetAgentBuffer',
                                             protos_dot_bff__pb2.ServiceIdList.SerializeToString,
                                             protos_dot_bff__pb2.AgentBufferMap.FromString, options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetAgentBuffer(request,
                       target,
                       options=(),
                       channel_credentials=None,
                       call_credentials=None,
                       insecure=False,
                       compression=None,
                       wait_for_ready=None,
                       timeout=None,
                       metadata=None):
        return grpc.experimental.unary_unary(request, target, '/game.bff.BFF/SetAgentBuffer',
                                             protos_dot_bff__pb2.AgentBufferMap.SerializeToString,
                                             protos_dot_types__pb2.CommonResponse.FromString, options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAgentStatus(request,
                       target,
                       options=(),
                       channel_credentials=None,
                       call_credentials=None,
                       insecure=False,
                       compression=None,
                       wait_for_ready=None,
                       timeout=None,
                       metadata=None):
        return grpc.experimental.unary_unary(request, target, '/game.bff.BFF/GetAgentStatus',
                                             protos_dot_bff__pb2.ServiceIdList.SerializeToString,
                                             protos_dot_bff__pb2.AgentStatusMap.FromString, options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetAgentStatus(request,
                       target,
                       options=(),
                       channel_credentials=None,
                       call_credentials=None,
                       insecure=False,
                       compression=None,
                       wait_for_ready=None,
                       timeout=None,
                       metadata=None):
        return grpc.experimental.unary_unary(request, target, '/game.bff.BFF/SetAgentStatus',
                                             protos_dot_bff__pb2.AgentStatusMap.SerializeToString,
                                             protos_dot_types__pb2.CommonResponse.FromString, options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SimControl(request,
                   target,
                   options=(),
                   channel_credentials=None,
                   call_credentials=None,
                   insecure=False,
                   compression=None,
                   wait_for_ready=None,
                   timeout=None,
                   metadata=None):
        return grpc.experimental.unary_unary(request, target, '/game.bff.BFF/SimControl',
                                             protos_dot_bff__pb2.SimCmd.SerializeToString,
                                             protos_dot_types__pb2.CommonResponse.FromString, options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SimMonitor(request,
                   target,
                   options=(),
                   channel_credentials=None,
                   call_credentials=None,
                   insecure=False,
                   compression=None,
                   wait_for_ready=None,
                   timeout=None,
                   metadata=None):
        return grpc.experimental.unary_unary(request, target, '/game.bff.BFF/SimMonitor',
                                             protos_dot_types__pb2.CommonRequest.SerializeToString,
                                             protos_dot_bff__pb2.SimInfo.FromString, options, channel_credentials, insecure,
                                             call_credentials, compression, wait_for_ready, timeout, metadata)
