#!/bin/bash

export SRC_DIR=3rd/rlframe-protos/src
export TAR_DIR=protos

# generate python files
python -m grpc_tools.protoc --proto_path=$SRC_DIR --python_out=$TAR_DIR --grpc_python_out=$TAR_DIR $SRC_DIR/*.proto

# generate FileDescriptorSet
python -m grpc_tools.protoc --include_imports --descriptor_set_out=descriptor.tmp --proto_path=$SRC_DIR $SRC_DIR/*.proto

# run post-processing to change absolute imports generated by protoc to relative imports
protol --create-package --in-place -s _pb2.py -s _pb2_grpc.py -o $TAR_DIR raw descriptor.tmp

# format python files
python -m yapf $TAR_DIR -i -p -r

# remove temporary files
rm descriptor.tmp
